apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ringlink-lb.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ringlink-lb.labels" . | nindent 4 }}
