apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ringlink-operator
    app.kubernetes.io/managed-by: kustomize
  name: {{ include "ringlink-lb.fullname" . }}-ringlink-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ringlink-lb.fullname" . }}-ringlink-operator-manager
subjects:
- kind: ServiceAccount
  name: ringlink-operator-sa
  namespace: '{{ .Release.Namespace }}'
