apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: ringlink-operator
    app.kubernetes.io/managed-by: kustomize
  name: ringlink-operator-sa
  namespace: {{ .Values.namespace }}
