apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ringlink-lb.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "ringlink-lb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ringlink-external-operator
      control-plane: controller-manager
    {{- include "ringlink-lb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ringlink-external-operator
        control-plane: controller-manager
      {{- include "ringlink-lb.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
        - args:
            - --metrics-bind-address=:8443
            - --leader-elect
            - --health-probe-bind-address=:8081
          command:
            - /manager
          env:
            - name: PROXY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "ringlink-lb.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
