apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ringlink-role
  labels:
  {{- include "ringlink-lb.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - patch
