apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ringlink-lb.fullname" . }}-ringlinkconfiguration-editor-role
  labels:
  {{- include "ringlink-lb.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ring.link
  resources:
  - ringlinkconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ring.link
  resources:
  - ringlinkconfigurations/status
  verbs:
  - get
