apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ringlink-lb.fullname" . }}-ringlinkconfiguration-admin-role
  labels:
  {{- include "ringlink-lb.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ring.link
  resources:
  - ringlinkconfigurations
  verbs:
  - '*'
- apiGroups:
  - ring.link
  resources:
  - ringlinkconfigurations/status
  verbs:
  - get
