namespace: ringlink-operator
deployment:
  name: ringlink-operator
  replicas: 1
image:
  repository: registry.ringlink.dev/pub/ringlink-operator
  tag: v0.2.1
  pullPolicy: Always
#imagePullSecrets: ""
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
