apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ringlink-role-binding
subjects:
  - kind: ServiceAccount
    name: ringlink-proxy
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: ringlink-role
  apiGroup: rbac.authorization.k8s.io
