apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ringlink-operator
  name: {{ include "ringlink-operator.fullname" . }}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ringlink-operator.fullname" . }}-ringlink-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: ringlink-operator-sa
  namespace: {{ .Release.Namespace }}
