apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ringlink-role
rules:
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "patch" ]
